### ISSUE TITLE
Advantages from the new IS - Task 7

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#10]

**Comment by JunKai-Li-1** [comment]
The implementation of the new information system into the in-house call management centre(CMC) could bring several benefits to the organisation and help them to gain the competitive advantage. The introduction of the information system will provide the Relationship managers’ profile and a skill matrix and customers’ information for the CMC to select the end-customers for providing a better quality server to the customer. 

CMC’s Information system enhanced the data access to alleviate the relationship managers’ time on spending into the harassing call and customer selecting to enhanced the overall efficiency, creates better sales and bring more value to the business. The software interaction with the Interactive Voice Response unit(IRP) and number identification does the caller authentication to the call to improve the security and handle the overflow calls to increase the communication and satisfaction  to the customer. It could reduce the cost from reducing the average calling time and number of employees required in order to provide more funds to the business.
