### ISSUE TITLE
Approach from Design Thinking Perspective

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#5]

**Comment by leongeitmann** [comment]
Copied from Code Task 3 Section (Please explain further, especially "Test" Section!)

Approach:  Design Thinking

Empathize
Empathy Map is sent to MS team, because GitHub doesn't allow to add graph in.


Define

In the Customer point of view,the interactive voice response(IVR) unit of the call management centre(CMC) result in a long
waiting time and hard to hear the unclear voice ,whcih it cause a loss of satisfaction and patient to the customer.The collects 
of information about customers' preferences and culture might infringe customers privacy. Also, the speed of responding 
time depends on the customer rating system causes an unfair treatment to the customer.


The features of system automatic dialling might disrupt the work rhythm of the relationship managers and result in 
an increased workload and low efficiency of work. The incorrect collection of relationship managers' detail might 
lead to the wrong information record in profile and a skill matrix, and final cause the system matched the relationship 
manager to the wrong customer.


In this system, a lot of RM information needs to be collected and matched with the user's information.
As the number of users increases, the time and energy required to manage the data will increase. If the data is not managed properly,
the user's information will easily be leaked


Ideate
Problem:a long waiting time and hard to hear the unclear voice.
Solution:Categorize problems and set up some that most customers might encounter, and set up a human service if the problem 
is not solved.

Problem:The features of system automatic dialling might cause an increased workload and low efficiency of work.
The RM worker can set his own working state in the system, and if the RM worker is already working, the system will automatically
skip his selection.

Problem:Customers' information may be leaked.
Solution: The privacy information of users to take encryption measures to prevent users from being harassed 
because of information disclosure。
Prototype
In MS Team.

Test
TC001 Login to the system
RM can only login with phone number and valid text verification.
TC002 See the main page
RM can choose what they want to do in this page
TC003 Browse current customers
RM can see the list about customer ranked by stars.
TC004 choosing
RM can press the phone button to talk with customers
TC005 Browse current recommend customers list
RM can see the list about recommended customer by system.
TC006 check the information
RM can check user detail in this system.
